//! OpenCade protocol — versioned envelope for REST + WebSocket messages.
//! Rust is the source of truth. TypeScript bindings under `src/generated/` are generated by
//! `ts-rs` and checked for drift in CI.
//!
//! # Wire format
//! Every message is an [`Envelope`] carrying `{ type, version, request_id, timestamp, payload }`.
//! Version `1.0` is canonical; `"1"` is accepted for backwards compatibility.
//! Payloads are strongly typed structs serialized with `snake_case` keys.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
use uuid::Uuid;

/// Canonical protocol version. All messages SHOULD use this value.
pub const PROTOCOL_VERSION: &str = "1.0";

/// Canonical schema version for redacted LAN alpha evidence reports.
pub const MATCH_REPORT_SCHEMA_VERSION: u8 = 1;

/// Canonical schema version for redacted alpha failure evidence.
pub const ALPHA_FAILURE_REPORT_SCHEMA_VERSION: u8 = 1;

/// Returns `true` if the supplied version string is supported.
///
/// Accepts both canonical `"1.0"` and compat `"1"`.
pub fn is_supported_version(v: &str) -> bool {
    v == "1.0" || v == "1"
}
/// Versioned envelope wrapping every protocol message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/Envelope.ts", concrete(T = String))]
pub struct Envelope<T = serde_json::Value> {
    /// Discriminator for message kind, e.g. `lobby.create`, `challenge.offer`.
    #[serde(rename = "type")]
    pub msg_type: String,
    /// Protocol version, e.g. "1.0".
    pub version: String,
    /// Unique id for request/response correlation.
    pub request_id: String,
    /// RFC 3339 timestamp (UTC).
    pub timestamp: DateTime<Utc>,
    /// Arbitrary payload.
    #[ts(type = "unknown")]
    pub payload: T,
}

impl<T> Envelope<T> {
    /// Create a new envelope with the canonical version, a fresh v4 UUID and `Utc::now()`.
    pub fn new(msg_type: impl Into<String>, payload: T) -> Self {
        Self {
            msg_type: msg_type.into(),
            version: PROTOCOL_VERSION.to_string(),
            request_id: Uuid::new_v4().to_string(),
            timestamp: Utc::now(),
            payload,
        }
    }

    /// Validate envelope fields.
    ///
    /// * `version` must be supported (`"1.0"` or `"1"`).
    /// * `msg_type` must be non-empty (after trimming).
    pub fn validate(&self) -> Result<(), String> {
        if !is_supported_version(&self.version) {
            return Err(format!("unsupported version: {}", self.version));
        }
        if self.msg_type.trim().is_empty() {
            return Err("msg_type must not be empty".to_string());
        }
        Ok(())
    }
}

impl Envelope<serde_json::Value> {
    /// Create a response correlated with an incoming request.
    pub fn reply(
        msg_type: impl Into<String>,
        request_id: impl Into<String>,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            msg_type: msg_type.into(),
            version: PROTOCOL_VERSION.to_string(),
            request_id: request_id.into(),
            timestamp: Utc::now(),
            payload,
        }
    }
}

// ---------------------------------------------------------------------------
// Payloads
// ---------------------------------------------------------------------------
/// Presence / latency update. Mirrors `diagnose_network` and `presence.update`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
#[ts(export, export_to = "../src/generated/PresencePayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct PresencePayload {
    pub user_id: String,
    pub rtt_ms: u32,
    pub loss: f32,
    pub jitter: u32,
    pub relay_reachable: bool,
}
/// Chat message. Used for `chat.message` in rooms/lobbies.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/ChatPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct ChatPayload {
    pub channel: String,
    pub body: String,
    pub author_id: String,
}
/// Challenge request between two users for a game/room.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/ChallengePayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct ChallengePayload {
    pub challenge_id: String,
    pub room_id: String,
    pub game_id: String,
    pub challenger_id: String,
    pub challenged_id: String,
    pub state: ChallengeState,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/ChallengeState.ts")]
#[serde(rename_all = "snake_case")]
pub enum ChallengeState {
    Pending,
    Accepted,
    Declined,
    Cancelled,
}

/// SDP offer relayed verbatim between authenticated room members.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/SessionOfferPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct SessionOfferPayload {
    pub room_id: String,
    pub sdp: String,
}

/// SDP answer relayed verbatim between authenticated room members.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/SessionAnswerPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct SessionAnswerPayload {
    pub room_id: String,
    pub sdp: String,
}

/// ICE candidate relayed verbatim between authenticated room members.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/SessionCandidatePayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct SessionCandidatePayload {
    pub room_id: String,
    pub candidate: String,
    pub sdp_mid: Option<String>,
    pub sdp_mline_index: Option<u16>,
}

/// Direct-UDP endpoint candidate exchanged between authenticated room members.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchEndpointPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct MatchEndpointPayload {
    pub room_id: String,
    pub endpoint: String,
    #[serde(default)]
    pub reflexive_endpoint: Option<String>,
    #[serde(default)]
    pub nat: NatMappingState,
    pub nonce: String,
}

/// Honest result of one STUN mapping observation. Cone/symmetric classification needs RFC 5780
/// behavior discovery and is deliberately not inferred from a single Binding transaction.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/NatMappingState.ts")]
#[serde(rename_all = "snake_case")]
pub enum NatMappingState {
    #[default]
    Unknown,
    Open,
    Mapped,
}

/// Candidate selected by the bounded direct-UDP traversal attempt.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchCandidateKind.ts")]
#[serde(rename_all = "snake_case")]
pub enum MatchCandidateKind {
    Host,
    Reflexive,
}

/// Result of a completed direct-UDP proof, relayed to the other room member.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchProbeCompletedPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct MatchProbeCompletedPayload {
    pub room_id: String,
    pub frames_received: u32,
    pub transcript_checksum: String,
}

/// Peer role retained in a redacted alpha report. User identifiers are deliberately omitted.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportRole.ts")]
#[serde(rename_all = "snake_case")]
pub enum MatchReportRole {
    Host,
    Guest,
}

/// Transport values accepted by the v1 alpha evidence contract.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportTransport.ts")]
#[serde(rename_all = "snake_case")]
pub enum MatchReportTransport {
    DirectUdp,
    Relay,
}

/// Privacy-minimized room correlation included in an alpha report.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportRoom.ts")]
pub struct MatchReportRoom {
    pub id: String,
    pub game_id: String,
    pub state: RoomState,
}

/// Deterministic transport evidence from one side of an alpha match.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportProbe.ts")]
pub struct MatchReportProbe {
    pub role: MatchReportRole,
    pub transport: MatchReportTransport,
    pub frames_sent: u32,
    pub frames_received: u32,
    pub transcript_checksum: String,
    pub elapsed_ms: u32,
    pub nat: Option<NatMappingState>,
    pub candidate: Option<MatchCandidateKind>,
    pub punch_attempts: Option<u8>,
}

/// Non-sensitive producer metadata used to diagnose platform-specific alpha failures.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportClient.ts")]
pub struct MatchReportClient {
    pub platform: String,
    pub user_agent: String,
}

/// Optional, privacy-safe hashes that let both peers prove identical native emulator inputs.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReportCompatibility.ts")]
pub struct MatchReportCompatibility {
    pub adapter: String,
    pub emulator_version: Option<String>,
    pub executable_sha256: String,
    pub core_sha256: String,
    pub content_sha256: String,
}

/// Stable stages for privacy-minimized evidence from an abandoned alpha attempt.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/AlphaFailureStage.ts")]
#[serde(rename_all = "snake_case")]
pub enum AlphaFailureStage {
    EndpointReservation,
    DirectUdp,
    RelayTicket,
    Relay,
    PeerTranscript,
    RoomTransition,
    NativeLaunch,
}

/// Discriminator that keeps failure evidence distinct from successful match reports.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/AlphaEvidenceKind.ts")]
#[serde(rename_all = "snake_case")]
pub enum AlphaEvidenceKind {
    AttemptFailure,
}

/// Canonical redacted evidence for an alpha attempt that did not complete.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/AlphaFailureReport.ts")]
pub struct AlphaFailureReport {
    pub schema_version: u8,
    pub kind: AlphaEvidenceKind,
    pub exported_at: DateTime<Utc>,
    pub room: MatchReportRoom,
    pub role: MatchReportRole,
    pub stage: AlphaFailureStage,
    pub error_code: String,
    pub transport: Option<MatchReportTransport>,
    pub client: MatchReportClient,
}

/// Canonical, redacted evidence emitted by both the desktop and standalone LAN probe.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/MatchReport.ts")]
pub struct MatchReport {
    pub schema_version: u8,
    pub exported_at: DateTime<Utc>,
    pub room: MatchReportRoom,
    pub probe: MatchReportProbe,
    pub client: MatchReportClient,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compatibility: Option<MatchReportCompatibility>,
}
/// Room lifecycle states. Serialized as `snake_case` strings.
/// ARCHITECTURE.md §9 DB stores WAITING/READY/PLAYING/FINISHED/CANCELLED (upper);
/// AGENTS.md describes WAITING→CHALLENGING→CONNECTING→PLAYING→FINISHED|CANCELLED.
/// Rust payload is snake_case lowercase for the wire; `Ready` is kept for compat with ARCH's READY.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/RoomState.ts")]
#[serde(rename_all = "snake_case")]
pub enum RoomState {
    Waiting,
    Ready,
    Challenging,
    Connecting,
    Playing,
    Finished,
    Cancelled,
}
/// Room snapshot pushed via `room.state`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
#[ts(export, export_to = "../src/generated/RoomPayload.ts")]
#[serde(rename_all = "snake_case")]
pub struct RoomPayload {
    pub id: String,
    pub game_id: String,
    pub host_id: String,
    pub guest_id: Option<String>,
    pub state: RoomState,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn roundtrip() {
        let env = Envelope::new("health.ok", json!({ "status": "ok" }));
        let s = serde_json::to_string(&env).unwrap();
        let back: Envelope = serde_json::from_str(&s).unwrap();
        assert_eq!(back.msg_type, "health.ok");
        assert_eq!(back.version, "1.0");
    }

    #[test]
    fn roundtrip_presence() {
        let payload = PresencePayload {
            user_id: "user-1".to_string(),
            rtt_ms: 42,
            loss: 0.02,
            jitter: 5,
            relay_reachable: true,
        };
        let env = Envelope::new("presence.update", payload.clone());
        let s = serde_json::to_string(&env).unwrap();
        let back: Envelope<PresencePayload> = serde_json::from_str(&s).unwrap();
        assert_eq!(back.payload, payload);
        assert_eq!(back.version, "1.0");
        assert!(back.validate().is_ok());
    }

    #[test]
    fn roundtrip_chat() {
        let payload = ChatPayload {
            channel: "lobby:1".to_string(),
            body: "hello".to_string(),
            author_id: "user-1".to_string(),
        };
        let env = Envelope::new("chat.message", payload.clone());
        let s = serde_json::to_string(&env).unwrap();
        let back: Envelope<ChatPayload> = serde_json::from_str(&s).unwrap();
        assert_eq!(back.payload, payload);
    }

    #[test]
    fn roundtrip_challenge() {
        let payload = ChallengePayload {
            challenge_id: "challenge-1".to_string(),
            room_id: "room-1".to_string(),
            game_id: "kof98".to_string(),
            challenger_id: "user-1".to_string(),
            challenged_id: "user-2".to_string(),
            state: ChallengeState::Pending,
        };
        let env = Envelope::new("challenge.create", payload.clone());
        let s = serde_json::to_string(&env).unwrap();
        let back: Envelope<ChallengePayload> = serde_json::from_str(&s).unwrap();
        assert_eq!(back.payload, payload);
    }

    #[test]
    fn roundtrip_session_messages() {
        let offer = SessionOfferPayload {
            room_id: "room-1".to_string(),
            sdp: "v=0\r\n...".to_string(),
        };
        let candidate = SessionCandidatePayload {
            room_id: "room-1".to_string(),
            candidate: "candidate:1 ...".to_string(),
            sdp_mid: Some("0".to_string()),
            sdp_mline_index: Some(0),
        };
        let offer_back: Envelope<SessionOfferPayload> = serde_json::from_str(
            &serde_json::to_string(&Envelope::new("signaling.offer", offer.clone())).unwrap(),
        )
        .unwrap();
        let candidate_back: Envelope<SessionCandidatePayload> = serde_json::from_str(
            &serde_json::to_string(&Envelope::new("signaling.candidate", candidate.clone()))
                .unwrap(),
        )
        .unwrap();
        assert_eq!(offer_back.payload, offer);
        assert_eq!(candidate_back.payload, candidate);
    }

    #[test]
    fn roundtrip_match_endpoint() {
        let payload = MatchEndpointPayload {
            room_id: "room-1".into(),
            endpoint: "192.168.1.20:42000".into(),
            reflexive_endpoint: Some("203.0.113.9:52000".into()),
            nat: NatMappingState::Mapped,
            nonce: "8a1110d5-8dd2-4ad2-9c88-ad9768bc4905".into(),
        };
        let encoded = serde_json::to_string(&Envelope::new("match.endpoint", payload.clone()))
            .expect("serialize endpoint");
        let decoded: Envelope<MatchEndpointPayload> =
            serde_json::from_str(&encoded).expect("deserialize endpoint");
        assert_eq!(decoded.payload, payload);
    }

    #[test]
    fn roundtrip_match_probe_completion() {
        let payload = MatchProbeCompletedPayload {
            room_id: "room-1".into(),
            frames_received: 60,
            transcript_checksum: "0376c2e852f4fd25".into(),
        };
        let encoded =
            serde_json::to_string(&Envelope::new("match.probe.completed", payload.clone()))
                .expect("serialize completion");
        let decoded: Envelope<MatchProbeCompletedPayload> =
            serde_json::from_str(&encoded).expect("deserialize completion");
        assert_eq!(decoded.payload, payload);
    }

    #[test]
    fn roundtrip_room() {
        let payload = RoomPayload {
            id: "room-1".to_string(),
            game_id: "kof98".to_string(),
            host_id: "user-1".to_string(),
            guest_id: Some("user-2".to_string()),
            state: RoomState::Waiting,
        };
        let env = Envelope::new("room.state", payload.clone());
        let s = serde_json::to_string(&env).unwrap();
        let back: Envelope<RoomPayload> = serde_json::from_str(&s).unwrap();
        assert_eq!(back.payload, payload);
    }

    #[test]
    fn room_state_variants_serde() {
        let cases = vec![
            (RoomState::Waiting, "waiting"),
            (RoomState::Ready, "ready"),
            (RoomState::Challenging, "challenging"),
            (RoomState::Connecting, "connecting"),
            (RoomState::Playing, "playing"),
            (RoomState::Finished, "finished"),
            (RoomState::Cancelled, "cancelled"),
        ];
        for (state, expected) in cases {
            let s = serde_json::to_string(&state).unwrap();
            assert_eq!(s, format!("\"{}\"", expected));
            let back: RoomState = serde_json::from_str(&s).unwrap();
            assert_eq!(back, state);
        }
    }

    #[test]
    fn room_payload_optional_guest() {
        let payload = RoomPayload {
            id: "room-2".to_string(),
            game_id: "sfiii3".to_string(),
            host_id: "user-1".to_string(),
            guest_id: None,
            state: RoomState::Waiting,
        };
        let s = serde_json::to_string(&payload).unwrap();
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert!(v.get("guest_id").is_some());
        let back: RoomPayload = serde_json::from_str(&s).unwrap();
        assert_eq!(back.guest_id, None);
    }

    #[test]
    fn type_field_renamed() {
        let env = Envelope::new("presence.update", json!({ "x": 1 }));
        let s = serde_json::to_string(&env).unwrap();
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert!(
            v.get("type").is_some(),
            "envelope must serialize msg_type as \"type\""
        );
        assert!(
            v.get("msg_type").is_none(),
            "envelope must not expose \"msg_type\" key"
        );
        assert_eq!(v["type"], "presence.update");
        // roundtrip rename
        let back: Envelope = serde_json::from_str(&s).unwrap();
        assert_eq!(back.msg_type, "presence.update");
    }

    #[test]
    fn snake_case_payload_keys() {
        let payload = PresencePayload {
            user_id: "user-1".to_string(),
            rtt_ms: 42,
            loss: 0.5,
            jitter: 7,
            relay_reachable: false,
        };
        let s = serde_json::to_string(&payload).unwrap();
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert!(v.get("rtt_ms").is_some(), "expected snake_case rtt_ms");
        assert!(v.get("user_id").is_some());
        assert!(v.get("relay_reachable").is_some());
        assert!(v.get("rttMs").is_none(), "must not be camelCase");
        assert!(v.get("relayReachable").is_none());
        // also check raw string contains snake_case
        assert!(s.contains("rtt_ms"));
        assert!(!s.contains("rttMs"));
    }

    #[test]
    fn snake_case_chat_keys() {
        let payload = ChatPayload {
            channel: "general".to_string(),
            body: "hi".to_string(),
            author_id: "user-1".to_string(),
        };
        let s = serde_json::to_string(&payload).unwrap();
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert!(v.get("author_id").is_some());
        assert!(v.get("authorId").is_none());
    }

    #[test]
    fn version_check() {
        assert_eq!(PROTOCOL_VERSION, "1.0");
        assert!(is_supported_version("1.0"));
        assert!(is_supported_version("1"));
        assert!(!is_supported_version("2.0"));
        assert!(!is_supported_version(""));
        assert!(!is_supported_version("1.1"));
    }

    #[test]
    fn validate_ok_and_err() {
        let mut env = Envelope::new("test.event", json!({}));
        assert!(env.validate().is_ok());

        env.version = "2.0".to_string();
        assert!(env.validate().is_err(), "unsupported version should fail");

        env.version = "1".to_string();
        assert!(
            env.validate().is_ok(),
            "\"1\" should be accepted for compat"
        );

        env.version = "1.0".to_string();
        env.msg_type = "".to_string();
        assert!(env.validate().is_err(), "empty msg_type should fail");

        env.msg_type = "   ".to_string();
        assert!(
            env.validate().is_err(),
            "whitespace-only msg_type should fail"
        );

        env.msg_type = "valid.type".to_string();
        assert!(env.validate().is_ok());
    }

    #[test]
    fn envelope_new_sets_expected_fields() {
        let env = Envelope::new("my.type", json!({ "a": 1 }));
        assert_eq!(env.msg_type, "my.type");
        assert_eq!(env.version, "1.0");
        assert!(!env.request_id.is_empty());
        // request_id should be valid UUID v4
        assert!(uuid::Uuid::parse_str(&env.request_id).is_ok());
    }

    #[test]
    fn reply_preserves_request_id() {
        let reply = Envelope::reply("pong", "request-123", json!({}));
        assert_eq!(reply.request_id, "request-123");
        assert_eq!(reply.msg_type, "pong");
    }
}
